# Generated by Django 3.1.7 on 2021-04-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20210403_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httprequest',
            name='url',
            field=models.URLField(),
        ),
    ]
