# Generated by Django 3.1.7 on 2021-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20210403_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='httprequest',
            name='load_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
